### PR TITLE
Update addons.yml

### PR DESCRIPTION
**Pull request by neurobashing**
add my git-branch extension

### CODE REVIEW

**Comment by Naatan** [comment]
Fyi rather than listening to load and use a timeout (eww) you can instead listen to `komodo-post-startup`.

**Comment by Naatan** [comment]
Just remembered we had this: http://beta.docs.komodoide.com/SDK/specs/events-and-notifications

**Comment by Naatan** [comment]
Btw mind if I rename it to "Git-Branch in Statusbar"? "Komodo" in the name is redundant.

**Comment by neurobashing** [comment]
sure. i only did that so it stands out in my Projects folder.

**Pull request merged**
