### PR TITLE
Update addons.yml: adding "Preference Spy"

### PR DESCRIPTION
**Pull request by ervumlens**
Adding "Preference Spy" extension: view all stored preferences and (to an extent) monitor preference changes.

### CODE REVIEW

**Comment by Naatan** [comment]
This is really cool! Awesome job!

I would suggest separating this from the pref window even (you could add a button in there to launch Pref spy), so that you don't have to be afraid of writing prefs. I could also see there being a stronger use-case for this living in it's own window rather than sharing the prefs window.

Regardless, awesome work. Been thinking about doing something like this as well (same type of thing as about:config). Glad you beat me to it :)

**Comment by ervumlens** [comment]
Thanks for looking it over and for the feedback, it's incredibly helpful.

> I would suggest separating this from the pref window even (you could add a button in there to launch Pref spy), so that you don't have to be afraid of writing prefs. I could also see there being a stronger use-case for this living in it's own window rather than sharing the prefs window.

That's a cool idea. It makes good sense too considering Pref Spy doesn't do updates like the other pref pages. (I put "Read-Only" in the item name to avoid confusion, which in hindsight is a sign it's in the wrong place.) The observer/logging code is *only* useful when writing prefs, so the whole thing could tie together better with a new window rather than in a set of related menu items.

:+1:

**Comment by Defman21** [comment]
You're beast @ervumlens!

**Comment by ervumlens** [comment]
@Defman21 :bear: &larr; self-portrait :stuck_out_tongue:

**Comment by Defman21** [comment]
Bear-programmer? Yeah, I've imagined you in the right way!

**Pull request merged**
