### PR TITLE
Added DockSearch add-on

### PR DESCRIPTION
**Pull request by Defman21**
[That](http://forum.komodoide.com/t/what-does-your-komodo-look-like/410/19?u=defman)

### CODE REVIEW

**Comment by Naatan** [comment]
Err.. this seems kind of redundant with Komodo 9.3's new docked search.. what does this do that our search does not?

**Comment by Defman21** [comment]
Nothing external, it uses find2.xul, just allows you to have it in different panes (left/right)

**Comment by Naatan** [comment]
"Nothing external"?

This will definitely break once 10.0 is released as it relies on old functionality (find2.xul) which will be removed.

Could you please add a disclaimer for this and recommend people to try the default search first? My fear with adding this to packages is that some people will come to rely on this without ever giving the existing functionality a chance simply because they have a BIAS for the more classical interface.

**Comment by Defman21** [comment]
You could simply not merging it though, I've created it because of a post on the forums and I thought that someone could use it too, but IMO the default search pane is awesome and distributing this add-on may cause some problems in the feature.

**Comment by Naatan** [comment]
Alright, if you don't feel strongly about it I'll close it. I can definitely see why some people would like this, but it's a bit risky and will likely cause issues down the road.

**Pull request closed without merging**
