### PR TITLE
added "Style Spy"

### PR DESCRIPTION
**Pull request by ervumlens**

### CODE REVIEW

**Comment by ervumlens** [comment]
Feedback requested. Let me know if everything looks okay.

**Comment by Defman21** [comment]
Can I ask you to describe your addon in 2 words? In which situations I can use the addon?

**Comment by Defman21** [comment]
Okay, nevermind, I got it. Nice work!

**Comment by ervumlens** [comment]
Thanks, defman. The tool's documentation is mostly in the tool itself, so it's very likely that some useful "marketing" details are missing from the Readme. Feel free to ask questions via [an issue](https://github.com/ervumlens/ko-stylespy/issues).

**Comment by Defman21** [comment]
I'm playing with it right ~~meow~~ now. Very interesting!

**Comment by Naatan** [comment]
This is pretty amazing @ervumlens! I'm impressed.

Ping @ericpromislow, you'll like this :)

**Comment by ericpromislow** [comment]
Yup, cool.

**Pull request merged**
