### PR TITLE
added font awesome and html entities side panel 

### PR DESCRIPTION
**Pull request by babobski**

### CODE REVIEW

**Comment by Naatan** [comment]
This is awesome, thanks for sharing! Note I will go in and suffix your titles with "Pane" so that it's less generic. Let me know if you prefer something else.

**Comment by babobski** [comment]
thanks, its fine with me, changed the readme's to reflect that naming.
Also changed panel in to pane assumed its a panel but is a pane.

**Comment by babobski** [comment]
updated readme so it looks good on github and komodoide

**Comment by Naatan** [comment]
Fyi this is how we tried to establish the terminology (we often still get it wrong ourselves):

Panel - the UI element you see at the left, right or bottom of your screen
Pane - any given visible "pane" within a panel
Widget - the actual content you're seeing, a pane can contain multiple widgets (ie. when you customize and combine them into a single pane)

So technically we got it wrong here, your addons are widgets, not panes. But the terminology is confusing, lets go with this for now. I think we need to revisit our terminology of these elements.

**Pull request merged**
