### PR TITLE
Added Tatu Diff and Smart tags auto-completion

### PR DESCRIPTION
**Pull request by babobski**
Added Tatu diff, this is a complete rebuild of my previous side by side diffviewer.
Also added Smart tags auto auto-completion, this is something I use on a daily bases, but I never added it to the packages.

### CODE REVIEW

**Comment by babobski** [comment]
Thanks!

**Comment by babobski** [comment]
Stupid me, forgot to add the releases.
Added them today.

**Comment by babobski** [comment]
@Naatan Can you kick it? the packages are stuck again, on the website.

**Comment by Naatan** [comment]
Done

**Pull request merged**
