### PR TITLE
added import servers addon

### PR DESCRIPTION
**Pull request by babobski**
Added a simple addon to import you're server settings between major Komodo releases.

### CODE REVIEW

**Comment by Naatan** [comment]
@babobski the issue of server settings not transferring was fixed in Komodo 11, are you saying it still doesnt work for you?

**Comment by babobski** [comment]
Thought only the projects issue was fixed.
The servers dit not get imported while developing this addon.
Just ran a clean install, with a new profile folder, and the servers do get imported.

**Comment by Naatan** [comment]
It would only import them when it creates the profile folder (the 11.0) on first start. I'm guessing you ran an earlier beta that did not contain the fix.

Just to be clear, this is working for you now on 11.0 using the latest RC?

**Comment by babobski** [comment]
Yes it is now working for me running the latest build.
The import servers functionality is now a bit obsolete for Komodo 11.
But it is still a good solution for Ko 9  and 10.

Think I'm going to extend the functionality so you can also export the server files to a different location, and import the settings from a different file location.
So if you want to transfer you're server settings between workstations it will help a hand.

**Comment by Naatan** [comment]
I think making it an export/import mechanic could be really useful, especially for teams. But I cannot accept it in its current state as it doesn't add any functionality. And people should be upgrading to 11, not 10 or an older version. I can see some edge cases where someone might want to do this, but in most cases this seems like someone would do this by mistake and we shouldn't be further facilitating that. Their solution is to update to 11.

**Comment by babobski** [comment]
I agree, closing it for now.

**Pull request closed without merging**
