### PR TITLE
Update userscripts.yml

### PR DESCRIPTION
**Pull request by krizoek**
Added tag-navigation and tag-index generator; these can be used separate or together

### CODE REVIEW

**Comment by Naatan** [comment]
hi @krizoek, you do not need to use all the extra fields you used, this is all inferred from your github repository. We only added support for this initially because we had a lot of packages which were not on github.

So if you don't mind please just change the format to `Name: github-url`, nothing else :)

**Comment by krizoek** [comment]
can i have fullpath there?, like this:
Tag Navigation: https://raw.githubusercontent.com/krizoek/komodo-comment-storage/master/CommentTagNav.js
Tag Index Generator: https://github.com/krizoek/komodo-comment-storage/raw/master/CommentStorageTags.js

**Comment by Defman21** [comment]
Nope.

**Comment by krizoek** [comment]
Think i'll rename the files first then, any suggestions on other things?

**Comment by Defman21** [comment]
You can't use raw.githubusercontent.com.

**Comment by krizoek** [comment]
what do you mean?

**Comment by Defman21** [comment]
https://github.com/krizoek/Packages/commit/11b041cfd0820305e1b577ab67da804206fb774d#diff-2b909db1453975b216e4802825e2e7f3R10 this

**Comment by krizoek** [comment]
ahh, i fixed it now :)

**Comment by Defman21** [comment]
I'm not sure for what reasons you have two items with the same github url. @Naatan?

**Comment by Naatan** [comment]
Almost there, you have all your userscripts in the same repo. For this to work they need to each be in their own repository. Public repositories don't cost a thing so it shouldn't matter too much :)

**Comment by krizoek** [comment]
Now it's done

**Comment by Naatan** [comment]
Perfect, thanks @krizoek !

Note that for people to be able to install your userscripts from within Komodo you need to upload the actual .komodotool file to the releases section of your repository.

**Comment by krizoek** [comment]
How can i do that when there is two .js files?

**Comment by Defman21** [comment]
I suppose that those js files are macros in your Komodo toolbox. If it's true - click on a macro and pick "Save As". Save it somewhere and then upload it as a release for your repo.

**Comment by krizoek** [comment]
Yes, but will they be able to install both from komodo if i release two releases of two different files?

**Comment by Defman21** [comment]
AFAIK they will able to install only one or nothing. Multiple files in one release is not something that Commando Packages can handle properly (yet).

**Comment by krizoek** [comment]
ok, i will make two repos first then

**Comment by Defman21** [comment]
Maybe I'm not right. It's better to wait for the answer from @Naatan.

**Pull request merged**
