### PR TITLE
Update schemes.yml

### PR DESCRIPTION
**Pull request by aryandb**

### CODE REVIEW

**Comment by Naatan** [comment]
Hi, first off thanks for sharing! Would you mind renaming your theme to something else? The name "Dracula" is in use, and the theme suffix is redundant.

**Comment by aryandb** [comment]
Hi I rename it to Halloween.

**Comment by Defman21** [comment]
ping @Naatan

**Comment by Naatan** [comment]
Thanks for the reminder @Defman21 :)

**Pull request merged**
