### PR TITLE
Update languages.yml

### PR DESCRIPTION
**Pull request by k-barton**
I added a link to my add-on "R interface"

### CODE REVIEW

**Comment by Naatan** [comment]
Hi @k-barton, I very much appreciate your hard work and your wanting to share it, but unfortunately as this is neither compatible with Komodo 10 nor 11 I cannot accept this. I'd be happy to provide assistance in adding compatibility.

**Comment by k-barton** [comment]
I've tried it now with Komodo 11 and it appears to work quite well, so I updated it setting maxVersion=11.  I noticed some minor glitches, so I have a few questions: 
- how do I register a language icon (for the "File Type" menu, and ideally also for files in "Places"). 
- icon on the "R objects" sidebar tab is gone in Ko 10/11, even though it is set as a <browser icon="..."> attribute. How to make it show up?

komodo11annot

**Comment by Naatan** [comment]
Unfortunately we have no way of specifying a custom icon for a custom language at the moment, I've logged a bug for this: https://github.com/Komodo/KomodoEdit/issues/3283

For the icon in the sidebar widget you need a CSS rule like this:

```
tab[widget="my-widget-id"] .tab-icon { 
  width: 14px;
  height: 14px;
  visibility: visible;
  background-image: url(...);
}
```

Note that the new codeintel in Komodo 11 does not yet facilitate addons, meaning that any codeintel hooks you have in your addon won't work in 11. This will be a part of the 11.1 update and should hopefully be a lot simpler to interface with than it has been.

That said, it looks like you have your own symbol browser widget rather than plugging into the codeintel one, so maybe this doesnt affect your addon?

**Comment by k-barton** [comment]
The autocompletion uses symbols that are retrieved from the connected R environment, so I am not sure if it will be at all possible to switch to the new codeintel. 

The CSS rule for a sidebar icon does not seem to work. Only a small rectangle shows up (instead of a blue "R"), but even this disappears when the colour scheme is changed. 
ko-sidebar-icon
Now I have:
* xul overlay:
```xml
<ko-pane id="workspace_left_area">
<browser type="ko-widget"
	id="rbrowser_tabpanel"
	label="&rBrowser.tab;"
	icon="chrome://komodor/skin/images/R_browser.svg"
	tab_onfocus="sv.rbrowser.focus();"
	src="chrome://komodor/content/rbrowser-pane.xul"
	/>
</ko-pane>
```
* css:
```css
tab[widget="rbrowser_tabpanel"] .tab-icon { 
  width: 14px;
  height: 14px;
  visibility: visible;
  background-image: url(chrome://komodor/skin/images/R_browser.svg);
}
```
The xul part is identical to that in e.g. "open files" widget (except for the icon url is "chrome:" rather than "ko-icon:"). Do you have any suggestions why is it so?

**Comment by Naatan** [comment]
You have to put a url that exists, `chrome://komodor/skin/images/R_browser.svg` is not an actual icon, unless you added it?

**Comment by k-barton** [comment]
It was an existing url (as evidenced by the blue background). Now I updated github copy with the modified files.

**Comment by Naatan** [comment]
I see, in that case you need to funnel it through koicon so the icon gets converted to a png. Komodo has issues with straight up showing PNG's.

Try this as the url:

```
koicon://ko-svg/chrome/komodor/skin/images/R_browser.svg?size=14
```

**Comment by k-barton** [comment]
That worked, thanks. So the "icon" attribute for <browser type="ko-widget"> does not have any effect?

**Comment by Naatan** [comment]
Not at the moment no, an oversight when it was implemented.

**Comment by k-barton** [comment]
I guess the extension is now compatible with Komodo 10-11. How do I proceed with adding it to the package list? Should I create another pull request?

I also noticed another annoyance, on Komodo side this time. In the sidebars, the scrollbar covers part of the content. This happens in "R browser" but also in "Toolbox".
ko-sidebar-scrollbar
In addition, the scrollbar sizing does not respect the system settings, which, I believe, it should.

**Comment by Naatan** [comment]
I tried running it in Komodo IDE, while it loads the toolbar buttons, syntax highlighting and file association stuff the sidebar widget does not seem to show any symbols. Does it require additional dependencies to work? I'd just like to make sure it does in fact work in Komodo 11.

**Comment by k-barton** [comment]
Yes, it needs an R environment installed on the system (https://cran.r-project.org/). After selecting R->Start R for the first time it should direct you to the preference page Languages->R where you can select from the installed R interpreters. At startup, R console should display something like: 
``` 
Server started at port NNNN 
Using R interface 0.1.341 on Komodo 9.3.2
```
and Command Output in Komodo should display a message `R version XXX is started`.
This would mean all went well and the R<->Komodo connection works fine.

**Comment by Naatan** [comment]
I can't seem to configure the interpreter, when I do so I get this error in the log:

```
[2017-10-17 13:57:10,903] [ERROR] prefs: 
-- EXCEPTION START --
TypeError: PrefR_CranMirrors[mirrorType][cmIdx] is undefined
+ stack
    OnPreferencePageOK@chrome://komodor/content/js/pref-R.js:286:2
    koPrefWindow.prototype._doOKHandlers@chrome://komodo/content/pref/koPrefWindow.js:252:26
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:328:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:370:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:361:16
    doOk@chrome://komodo/content/pref/pref.js:59:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:117:22
    openDialogWrap@chrome://komodo/content/komodo.js:641:19
    openDialogUniqueInstance@chrome://komodo/content/library/windowManager.js:69:19
    prefs_doGlobalPrefs@chrome://komodo/content/pref/prefs.js:27:13
    this.startR@chrome://komodor/content/js/commands.js:161:5
    @chrome://komodor/content/js/commands.js line 428 > eval:1:1
    _setControllers/broadcasterController.prototype.doCommand@chrome://komodor/content/js/commands.js:428:1
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --
```

**Comment by k-barton** [comment]
What OS do you use?

**Comment by Naatan** [comment]
Linux

**Comment by k-barton** [comment]
Can you try the updated version? I couldn't replicate the error you got, but I fixed a number of other Linux-related problems and now it appears to work fine (with Komodo Edit). This error may be specific to IDE though.

**Comment by Naatan** [comment]
I just noticed the release you have published is from May:

https://github.com/k-barton/komodor/releases

That's probably part of the reason I was having issues. Please note you need to add a new release each time, as that is what our Packages site will publish to the user :)

**Comment by k-barton** [comment]
Ok, I see. I've been just replacing the .xpi and increasing version number. I didn't notice this way the publication date does not change. Anyway I keep only one release, so you've been probably using the right one (the current version is 0.1.359)

**Comment by Naatan** [comment]
ah, I would recommend just adding a new release each time. You can always delete the old one, but it doesn't cost you anything to keep the old one around. I think just updating the same one each time might screw up the updating mechanic in Komodo (it won't detect new versions).

More to the point, I just tested your latest xpi and it appears to be working :) Thanks for the hard work! I'll go ahead and merge this.

**Comment by k-barton** [comment]
Nice. Many thanks for help. There is still a lot of things to improve, but the basic functionalities are there.

BTW is there any chance you add a native system styling scheme to Komodo? That is something that stops me from using the new versions. The "classic mode" doesn't really work. On Windows it does not conform to some system standards like dialog button ordering or scrollbar sizing.

**Pull request merged**
