### PR TITLE
Added my last modified files addon

### PR DESCRIPTION
**Pull request by babobski**
Last weekend I was stuck on how to implement the tooltip, so i crafted this addon to finish the weekend with some happy coding :smile: 
Tested it and optimalised it this week, and now it's ready for the community.
Its a small addon witch keeps track of the last modified files(adds the file on save to the list), you can see the last modified files in a new window, by clicking on the item you will open or goto the file.

### CODE REVIEW

**Comment by Naatan** [comment]
Looks great, thanks for sharing! :)

Note this could also work very well as a commando scope :)

**Comment by babobski** [comment]
no problem, 
> Note this could also work very well as a commando scope :)

Was thinking about your answer, but didn't quit get what you meant.
Like seeing you're last entered commando's?

**Comment by Naatan** [comment]
Commando - Go to anything. Ie. you hit "Ctrl+Shift+O" and you have a "Last modified files" scope that lists files and lets you open them.

**Comment by babobski** [comment]
ah i get it, like the server scope from @Defman21, but only then with a last modified files scope.

**Comment by Naatan** [comment]
Yes, exactly.

**Pull request merged**
