### PR TITLE
Update schemes.yml

### PR DESCRIPTION
**Pull request by krizoek**
Added NeutralEye Scheme

### CODE REVIEW

**Comment by Naatan** [comment]
Very nice! Thanks for sharing! :)

**Comment by Defman21** [comment]
@Naatan this is broken! @krizoek forgot to put ":" after the name of the theme.
`NeutralEye: https://github.com/krizoek/Komodo_NeutralEye` is correct.

**Comment by Naatan** [comment]
I know, I fixed it already :)

**Comment by Defman21** [comment]
Daym u r fast!
18.12.2015 20:46 пользователь "Nathan Rijksen" <notifications@github.com>
написал:

**Comment by Naatan** [comment]
Actually you noticed it faster than I did, I only noticed cause the build was breaking :p

**Pull request merged**
